### ISSUE TITLE
when i run map.py, i came across an error"AttributeError: 'Game' object has no attribute 'serve_car' '"

### ISSUE THREAD

**Issue by mengfansheng16** [Jerry2001Qu/Self-Driving-Car#1]
Traceback (most recent call last):    
   File "map.py", line 242, in <module>      
      CarApp().run()    
   File "/usr/local/lib/python3.5/dist-packages/kivy/app.py", line 800, in run      
       root = self.build()    File "map.py", line 210, in build      parent.serve_car() 
    **AttributeError: 'Game' object has no attribute 'serve_car'**

can you help ? thx

**Comment by host452b** [comment]
me too~
 Traceback (most recent call last):
   File "map.py", line 242, in <module>
     CarApp().run()
   File "/home/joe/.local/lib/python3.6/site-packages/kivy/app.py", line 800, in run
     root = self.build()
   File "map.py", line 210, in build
     parent.serve_car()
   File "map.py", line 109, in serve_car
     self.car.center = self.center
 AttributeError: 'NoneType' object has no attribute 'center'

**Comment by SuperBianC** [comment]
I met with this too. I found that in App.py there is a function _def build(self)_, you can change the name of build to build2(self) for example. Then you change the _build_ in _root = build(self)_ to _root = build2(self)_  . And it will work. Go and have Fun.

**Comment by storm064** [comment]
> I met with this too. I found that in App.py there is a function _def build(self)_, you can change the name of build to build2(self) for example. Then you change the _build_ in _root = build(self)_ to _root = build2(self)_ . And it will work. Go and have Fun.

Where is app.py?  I first thought aii.py is the file (just thought it was a typo). But there was no def build(self) in that code.

**Comment by Caesar8080** [comment]
> 我也遇到了这个。我发现App.py中有一个函数_def build（self）_，例如，您可以将build的名称更改为build2（self）。然后，你改变了_构建_中_的root =构建（个体经营）_到_根= build2中（个体经营）_ 。它将起作用。去玩吧。

I did what you said，and then computer resolution changes, screen goes black，nothing happened

**Comment by swb19** [comment]
> me too~
> Traceback (most recent call last):
> File "map.py", line 242, in
> CarApp().run()
> File "/home/joe/.local/lib/python3.6/site-packages/kivy/app.py", line 800, in run
> root = self.build()
> File "map.py", line 210, in build
> parent.serve_car()
> File "map.py", line 109, in serve_car
> self.car.center = self.center
> AttributeError: 'NoneType' object has no attribute 'center'

You can change the map.py:
class Game(Widget):

    car = Car()
    ball1 = Ball1()
    ball2 = Ball2()
    ball3 = Ball3()

    # car = ObjectProperty(None)
    # ball1 = ObjectProperty(None)
    # ball2 = ObjectProperty(None)
    # ball3 = ObjectProperty(None)

Hope to help you
